feat: 메모 저장 검색 기능 작성
swm-null/null_backend pull request #2
Opened 2024-06-27 17:34 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #1 

# 🚀 작업 내용

1. 피드백 반영
2. 메모 저장 기능
3.  찾기 기능
4. 저장 기능
5. 환경변수 처리
6. 예외처리
7. swagger 수정

# 💬 리뷰 중점사항

restTemplate 커스텀 예외처리를 만들었는데 잘 동작하는건지 확인 필요.

git ignore 세팅을 처음에 풀어두었다가 대참사남.. (자잘한 파일들 무시바랍니다.) -> ignore세팅했는데 push되면 적용되는지

2024-06-27 18:22 UTC, gee2450 requested changes

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/MemoService.java
> +            case 3 -> searchMemoByTag(aiSearchResponse.content().get(0), memoResponseBridgeList);
보기 쉽게 type Integer 말고 string으로 변경할 꺼라고 하지 않았었나? 
혹시 까먹으신 건가요, 아니면 나중에 하려고 미루신건가요?

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/RestTemplateService.java
> +        return aiResponse.getBody();
오 spring은 setErrorHandler 저거 하면 모든 에러는 다 잡히는 건가요? 멋지네요
front도 그런거 있나 찾아봐야겠어요

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/RestTemplateService.java
> +        ResponseEntity<AiSearchResponse> aiResponse = restTemplate.getForEntity(uri, AiSearchResponse.class);
String.format("%s%s%s", aiUrl, query, content)으로 보니깐 좀 복잡한데 spring에는 혹시 
\`${aiUrl}/user_query?query=${content}\` <- 이런 느낌은 못 쓰나요? 없으면 아쉬운거고...

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/exception/AiResponseErrorHandler.java
어...제가 코드를 잘 이해 못한 것 같긴한데, AiResponsErroHandler가 정확히 뭐죠? 
be <-> ai 서버 response 핸들링하는 class인 줄 알았는데 왜 Client 오류와 Server 오류가 있는거죠?

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/models/MemoRequestBridge.java
> +    public static Memo toMemo(String memoId, List<String> tags, String content) {
파라미터가 MemoRequestBridge 일때는, spring 모르는 입장에서 직접 파일로 들어가서 봐야했었는데, 훨씬 보기 좋아졌네요. 
굳굳

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/models/Memo.java
> -
이건 왜 삭제된거죠? commit 제목은 메모 생성 기능 추가였는데
다른 쪽 코드로 이동한건가요?

2024-06-27 18:22 UTC, gee2450 commented on src/main/java/com/example/memo/_config/RestTemplateConfig.java
이 Class는 잘 만든 것 같은데 아무곳에서도 안 쓰이는 것 같은데 맞나요? 
restTemplate 생성하고 setErrorHandler하면 매번 따로 
restTemplate.setErrorHandler(new AiResponseErrorHandler());안해도 될 것 같아 좋아보이는데,
이 파일의 쓰임새는 뭔가요?

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/_config/RestTemplateConfig.java
저거 써놓고 다른 파일의 restTemplate.setErrorHandler를 안지워놨었네요. 실제로는 쓰이는 중 입니다.

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/MemoService.java
> +            case 3 -> searchMemoByTag(aiSearchResponse.content().get(0), memoResponseBridgeList);
아직 AI쪽에서 변경이 안돼서 유지중입니다.

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/RestTemplateService.java
> +        return aiResponse.getBody();
restTemplate에서 자체적으로 에러 던지는거를 수정하기 위해 커스텀에러핸들러 만들어서 사용한 것입니다

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/exception/AiResponseErrorHandler.java
백엔드단에서 ai서버단으로 요청을 날리고 응답이 4xx, 5xx에러의 경우 자체적으로 예외처리하기 위해 만든 것입니다.

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/models/Memo.java
> -
기존에는
 저장->ai보내기-> 수정 으로 하려다가
 ai보내기-> 저장 으로 간편화 시켰습니다.

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/models/MemoRequestBridge.java
> +    public static Memo toMemo(String memoId, List<String> tags, String content) {
이건 전에 급하게 만드느라 이상하게 만든부분 수정했습니다. 엔티티가 DTO에 의존성 줄이는 방식과 같다고 보시면될것 같습니다.

2024-06-27 18:33 UTC, BaeJinho4028 commented on src/main/java/com/example/memo/memo/service/RestTemplateService.java
> +        ResponseEntity<AiSearchResponse> aiResponse = restTemplate.getForEntity(uri, AiSearchResponse.class);
깔끔한 builder방식이 있는데, 그거 쓰면 띄어쓰기가 자동으로 인코딩돼서
ex) 민지 전번 메모 찾아줘 -> 민지%20전번%20메모%20찾아줘 
이렇게 되더라구요.. 좀더 좋은 방법을 찾아보겠습니다.

2024-06-27 18:35 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/RestTemplateService.java
> +        ResponseEntity<AiSearchResponse> aiResponse = restTemplate.getForEntity(uri, AiSearchResponse.class);
흠..아쉽네요.

2024-06-27 18:38 UTC, gee2450 commented on src/main/java/com/example/memo/memo/service/exception/AiResponseErrorHandler.java
그럼 handleError를 좀 더 명확하게 해주시면 좋을 것 같습니다.
ex) "ai 서버 오류" 와 "be 클라이언트 오류"

2024-06-27 18:38 UTC, gee2450 commented on src/main/java/com/example/memo/_config/RestTemplateConfig.java
뭐야 진짜? 뭐지 제 인텔리제이가 일을 안해요

2024-06-27 18:58 UTC, gee2450 approved these changes

2024-06-28 05:27 UTC, r4pidstart commented on src/main/java/com/example/memo/memo/service/MemoService.java
> +            case 3 -> searchMemoByTag(aiSearchResponse.content().get(0), memoResponseBridgeList);
말해주면 바로 했을텐데 ㅋㅋ

2024-06-28 05:29 UTC, r4pidstart approved these changes
lgtm~

2024-06-28 06:17 UTC, merged